### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by RWOverdijk** [enjikaka/webrtc-audio-stream#1]
I'm getting a: 

> Uncaught (in promise) DOMException: Cannot decode detached ArrayBuffer

It looked promising, hope you can tell me what I'm doing wrong.

**Comment by enjikaka** [comment]
Hello! Thanks for trying out the project. :) 

Just fixed the issue in the master branch. The problem was that somewhere along the way ArrayBuffer got detached before reaching decodeAudioData, probably due to WaveformGenerator using it before the audio decoding. 

Here's the commit that fixes the issue if you're interested: 
https://github.com/enjikaka/webrtc-audio-stream/commit/97040204de9a10deb21196893b55f87592300406

There are quite a few things that doesn't work anymore, but I tried and with this fix streaming works again at least.
